### ISSUE TITLE
🔥 RoR group project: set up your Kanban board 

### ISSUE THREAD

**Issue by roniy68** [roniy68/recipe-app#10]
# Highlights 🥇 

<img src="https://media0.giphy.com/media/3ov9jZafEefHLyTf8c/giphy.gif"/>

## What I Have Done: 
✅ Create an empty repository for your group project.
✅ Open the GitHub project (Kanban board) in your team repo (set up the same columns as in previous group projects).
✅ Open [project requirements](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md) and read them carefully.
✅ Create tasks on your Kanban board based on the [project requirements](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md).

# Project : 
## 👥 Authors

- Ahmed Hassan Rony @roniy68 
- Muhammad Aleem @MAleemH 

***NOTE: WE HAVE TWO TEAM MEMBERS IN OUR GROUP***

## Missed anything?
- [ ] Explained the purpose of this ISSUE.
- [ ] Self reviewed the ISSUE.
- [ ] Added or updated test cases.
- [ ] Informed of breaking changes, testing and migrations (if applicable).
- [ ] Updated documentation (if applicable).
- [ ] Attached screenshots (if applicable).

## Followed Rules: 
- Made sure [no linter errors](https://github.com/microverseinc/linters-config)
-  Followed [Github Flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md)
-  Documented [professionaly](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)
- Follow our list of [best practices for Ruby](https://github.com/microverseinc/curriculum-ruby/blob/main/articles/ruby_best_practices.md).

**Comment by gemmen29** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 💯  
- Descriptive info ✔️
- Tasks distributed equally ✔️  

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Required Changes ♻️
- [ ] Kindly add a card to the kanban board that represents this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md#:~:text=General%20shopping%20list%20view%20(only%20for%20a%20group%20that%20has%20less%20than%203%20members)). The General shopping list should be implemented if the group has less than 3 members.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by roniy68** [comment]
The general Shopping List Removed 😄
